# Generated by Django 5.2.8 on 2025-11-25 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MOCK_DOCS', 'Mock - dokumenty (docs)'), ('MOCK_ERP', 'Mock - ERP snapshot'), ('MOCK_MES', 'Mock - MES snapshot'), ('USER_UPLOAD', 'Upload użytkownika')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('mock_stream', models.CharField(blank=True, max_length=16)),
                ('mock_version_date', models.DateField(blank=True, null=True)),
                ('mock_filename', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
